version: "3"

services:
  web:
    build: .
    container_name: django_aiogram
    command: bash -c "python manage.py bot && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
